name: 2.1$(Rev:.r)-modified

resources:
  repositories:
    - repository: templates
      type: github
      name: goformz/devops-templates
      endpoint: github

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

steps:
- template: build-nuget-netcore.yml@templates
  parameters:
    runTests: false
    workingDirectory: '.'